# Generated by Django 3.2.16 on 2023-11-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('min_price', models.PositiveSmallIntegerField(verbose_name='Минимальная цена')),
                ('max_price', models.PositiveSmallIntegerField(verbose_name='Максимальная цена')),
                ('min_sells', models.PositiveSmallIntegerField(verbose_name='Мин. количество продаж в день')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=32, verbose_name='SKU')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('brand', models.CharField(max_length=64, verbose_name='Бренд')),
                ('thumb', models.CharField(max_length=256, verbose_name='Картинка 1')),
                ('thumb_middle', models.CharField(max_length=256, verbose_name='Картинка 2')),
                ('median_price', models.CharField(max_length=16, verbose_name='Финальная цена')),
                ('sku_first_date', models.DateTimeField(verbose_name='Дата появления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='comps.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'тренд',
                'verbose_name_plural': 'Тренды',
            },
        ),
    ]
