# Generated by Django 3.2.16 on 2023-11-15 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='sku',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='comps.category', verbose_name='Категория'),
        ),
    ]
