# Generated by Django 3.2.16 on 2023-11-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0003_auto_20231116_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id_wb',
            field=models.CharField(blank=True, max_length=10, verbose_name='ID для API'),
        ),
    ]
