# Generated by Django 3.2.16 on 2023-11-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0005_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['id'], 'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
