# Generated by Django 3.2.16 on 2023-12-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0008_category_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Исключенный бренд',
                'verbose_name_plural': 'Исключенные бренды',
            },
        ),
        migrations.CreateModel(
            name='ExcNaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, verbose_name='Слово исключение')),
            ],
            options={
                'verbose_name': 'Слова-исключения для названия',
                'verbose_name_plural': 'Слова-исключения для названия',
            },
        ),
        migrations.RemoveField(
            model_name='sku',
            name='avg_sells14',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='avg_sells21',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='avg_sells30',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='avg_sells8',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='boost14',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='boost21',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='boost30',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='boost8',
        ),
        migrations.AddField(
            model_name='category',
            name='fix_avg_sells',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Фикс. сред. количество продаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='avg_sells_growth14',
            field=models.BooleanField(blank=True, default=1, verbose_name='Флаг роста продаж 14 дней'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='avg_sells_growth21',
            field=models.BooleanField(blank=True, default=1, verbose_name='Флаг роста продаж 21 день'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='avg_sells_growth30',
            field=models.BooleanField(blank=True, default=1, verbose_name='Флаг роста продаж 30 дней'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='avg_sells_growth8',
            field=models.BooleanField(blank=True, default=1, verbose_name='Флаг роста продаж 8 дней'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='fix_avg_14',
            field=models.BooleanField(blank=True, default=1, verbose_name='Фиксированные средние продажи 14 дней'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='fix_avg_21',
            field=models.BooleanField(blank=True, default=1, verbose_name='Фиксированные средние продажи 21 день'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='fix_avg_30',
            field=models.BooleanField(blank=True, default=1, verbose_name='Фиксированные средние продажи 30 дней'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='fix_avg_8',
            field=models.BooleanField(blank=True, default=1, verbose_name='Фиксированные средние продажи 8 дней'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='min_avg_sells14',
            field=models.BooleanField(blank=True, default=1, verbose_name='Критерий минимального среднего 14 дней'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='min_avg_sells21',
            field=models.BooleanField(blank=True, default=1, verbose_name='Критерий минимального среднего 21 день'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='min_avg_sells30',
            field=models.BooleanField(blank=True, default=1, verbose_name='Критерий минимального среднего 30 дней'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='min_avg_sells8',
            field=models.BooleanField(blank=True, default=1, verbose_name='Критерий минимального среднего 8 дней'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='min_sells',
            field=models.PositiveSmallIntegerField(verbose_name='Мин. сред. количество продаж'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='stocks14',
            field=models.BooleanField(blank=True, verbose_name='Флаг остатков 8 дней'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='stocks21',
            field=models.BooleanField(blank=True, verbose_name='Флаг остатков 8 дней'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='stocks30',
            field=models.BooleanField(blank=True, verbose_name='Флаг остатков 8 дней'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='stocks8',
            field=models.BooleanField(blank=True, verbose_name='Флаг остатков 8 дней'),
        ),
        migrations.DeleteModel(
            name='Sku_stats8',
        ),
    ]
