# Generated by Django 3.2.16 on 2023-12-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0009_auto_20231206_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='revenue',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Выручка'),
        ),
    ]
