# Generated by Django 3.2.16 on 2023-12-17 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0010_sku_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='fav',
        ),
        migrations.AddField(
            model_name='favorites',
            name='brand',
            field=models.CharField(blank=True, max_length=64, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favs', to='comps.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorites',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='sku_first_date',
            field=models.DateTimeField(default=datetime.date(2023, 12, 17), verbose_name='Дата появления'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='sku_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='thumb_middle',
            field=models.CharField(blank=True, max_length=256, verbose_name='Картинка 1'),
        ),
    ]
