# Generated by Django 3.2.16 on 2024-01-10 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comps', '0011_auto_20231217_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='min_total_sells',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Мин. количество продаж'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorites',
            name='sku_first_date',
            field=models.DateTimeField(default=datetime.date(2024, 1, 10), verbose_name='Дата появления'),
        ),
    ]
